spring.application.name=ms-product
server.port=8082


# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://172.31.252.28:5432/product-db
spring.datasource.username=postgres
spring.datasource.password=SIRIUS
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.show-sql=true
# Met à jour automatiquement la structure de la base de données selon tes entités Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect