version: '3.8'

services:
  ms-membership:
    build: 
      context: ./ms-membership 
    ports:
      - "8081:8081"
    networks:
      - epigreen-network

  ms-product:
    build: 
      context: ./ms-product
    ports:
      - "8082:8082"
    networks:
      - epigreen-network

  ms-cart:
    build: 
      context: ./ms-cart
    ports:
      - "8083:8083"
    environment:
      - MS_PRODUCT_URL=http://ms-product:8082
    networks:
      - epigreen-network
    depends_on:
      - ms-product

networks:
  epigreen-network:
    driver: bridge