spring.application.name=ms-telemetry

server.port=8088
spring.kafka.bootstrap-servers=172.31.249.79:9092
spring.kafka.consumer.group-id=telemetry-group
spring.kafka.consumer.auto-offset-reset=earliest
api.delivery.url=http://ms-delivery:8087/api/delivery
mqtt.broker.url=tcp://mosquitto:1883

logging.level.root=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN