spring.application.name=ms-order

# Port du microservice Order
server.port=8084


# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://172.31.252.28:5432/order-db
spring.datasource.username=postgres
spring.datasource.password=SIRIUS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === NOTRE VARIABLE POUR OPENFEIGN ===
cart.service.url=http://ms-cart:8083

# --- CONFIGURATION DES LOGS ---
logging.level.root=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN
logging.level.ms_order=DEBUG

