spring.application.name=ms-notification
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
google.credentials.location=classpath:credentials.json
# Liste des emails autorisés séparés par des virgules
app.notification.whitelist=nawel.cloudlab@gmail.com,nawres.tns@gmail.com,seulgi.shin.fr@gmail.com,ghazal.nawel@gmail.com

# --- CONFIGURATION DES LOGS ---
logging.level.root=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN