# Application
spring.application.name=spark-monitor

# Actuator 
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted

# SSH connexion vers Spark Master
spark.ssh.host=172.31.253.136
spark.ssh.user=hadoop
spark.ssh.port=22

# Job1 
spark.job1.remoteScript=/home/hadoop/jobs/run_job1_detournement.sh

# Job2 
spark.job2.remoteScript=/home/hadoop/jobs/run_job2_service.sh