spring.application.name=spark-monitor
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
spark.ssh.host=172.31.253.136
spark.ssh.user=hadoop
spark.ssh.port=22

# Chemin du script à exécuter sur la VM spark master
spark.job1.remoteScript=/home/hadoop/jobs/run_job1_detournement.sh
