server:
  port: 8087

spring:
  application:
    name: ms-delivery

  kafka:
    bootstrap-servers: 172.31.249.79:9092
  
  datasource:
    url: jdbc:postgresql://172.31.252.74:5432/delivery-db
    username: postgres
    password: SIRIUS
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR 
    org.hibernate.type.descriptor.sql: ERROR
    org.springframework.kafka: WARN 
    org.apache.kafka: WARN
    ms_delivery: DEBUG

geoapify:
  key: ${GEOAPIFY_API_KEY}